server:
  port: 8080

spring:
  r2dbc:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    clean-on-validation-error: true
    baseline-on-migrate: true
    clean-disabled: false